export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const ACTIVE_FACULTY = 'ACTIVE_FACULTY'
export const RETRIEVE_PROFILE = 'RETRIEVE_PROFILE'
export const LOAD_PROFILE = 'LOAD_PROFILE'
export const PROFILE_NO_DATA = 'PROFILE_NO_DATA'
export const RESET_PROFILE = 'RESET_PROFILE'
export const RETRIEVE_MULTIPLE_PROFILES = 'RETRIEVE_MULTIPLE_PROFILES'


export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
